version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino_pass
      POSTGRES_DB: casino_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: 